packages:
  - packages/*
  - tools/*
  - services/*

onlyBuiltDependencies:
  - '@bufbuild/buf'
  - '@swc/core'
  - core-js
  - esbuild
  - msw
  - nx
  - protobufjs
  - secp256k1
  - sharp
  - unrs-resolver
