/**
 * Peg-in Manager - Wallet Orchestration for Peg-in Operations
 *
 * This module provides the PeginManager class that orchestrates the complete
 * peg-in flow using SDK primitives, utilities, and wallet interfaces.
 *
 * @remarks
 * PeginManager handles the peg-in flow:
 * 1. **preparePegin()** - Build Pre-PegIn HTLC, fund it, sign PegIn input
 * 2. **registerPeginOnChain()** - Submit to Ethereum contract with PoP
 * 3. *(Use {@link PayoutManager} for payout authorization signing)*
 * 4. **signAndBroadcast()** - Sign and broadcast Pre-PegIn tx to Bitcoin network
 *
 * @see {@link PayoutManager} - For Step 3: sign payout transactions
 * @see {@link buildPrePeginPsbt} - Lower-level primitive used internally
 *
 * @module managers/PeginManager
 */

import * as bitcoin from "bitcoinjs-lib";
import { Psbt, Transaction } from "bitcoinjs-lib";
import { Buffer } from "buffer";
import {
  createPublicClient,
  encodeFunctionData,
  http,
  zeroAddress,
  type Address,
  type Chain,
  type Hex,
  type WalletClient,
} from "viem";

import type { BitcoinWallet, Hash, SignPsbtOptions } from "../../../shared/wallets";
import { createTaprootScriptPathSignOptions } from "../utils/signing";
import { type UtxoInfo, getUtxoInfo, pushTx } from "../clients/mempool";
import { BTCVaultRegistryABI, handleContractError } from "../contracts";
import {
  buildPrePeginPsbt,
  buildPeginTxFromFundedPrePegin,
  buildPeginInputPsbt,
  extractPeginInputSignature,
  finalizePeginInputPsbt,
  deriveVaultId,
  type PrePeginParams,
  type Network,
} from "../primitives";
import {
  ensureHexPrefix,
  isAddressFromPublicKey,
  stripHexPrefix,
} from "../primitives/utils/bitcoin";
import {
  calculateBtcTxHash,
  fundPeginTransaction,
  getNetwork,
  getPsbtInputFields,
  peginOutputCount,
  selectUtxosForPegin,
  type UTXO,
} from "../utils";

/** Referral code sent with pegin registration — 0 means no referral. */
const NO_REFERRAL_CODE = 0;

/**
 * Configuration for the PeginManager.
 */
export interface PeginManagerConfig {
  /**
   * Bitcoin network to use for transactions.
   */
  btcNetwork: Network;

  /**
   * Bitcoin wallet for signing peg-in transactions.
   */
  btcWallet: BitcoinWallet;

  /**
   * Ethereum wallet for registering peg-in on-chain.
   * Uses viem's WalletClient directly for proper gas estimation.
   */
  ethWallet: WalletClient;

  /**
   * Ethereum chain configuration.
   * Required for proper gas estimation in contract calls.
   */
  ethChain: Chain;

  /**
   * Vault contract addresses.
   */
  vaultContracts: {
    /**
     * BTCVaultRegistry contract address on Ethereum.
     */
    btcVaultRegistry: Address;
  };

  /**
   * Mempool API URL for fetching UTXO data and broadcasting transactions.
   * Use MEMPOOL_API_URLS constant for standard mempool.space URLs, or provide
   * a custom URL if running your own mempool instance.
   */
  mempoolApiUrl: string;
}

/**
 * Parameters for the pegin flow (pre-pegin + pegin transactions).
 */
export interface PreparePeginParams {
  /**
   * Amounts to peg in per HTLC (in satoshis).
   * Must have the same length as `hashlocks`.
   * For single deposits, pass a single-element array.
   */
  amounts: readonly bigint[];

  /**
   * Vault provider's BTC public key (x-only, 64-char hex).
   * Can be provided with or without "0x" prefix (will be stripped automatically).
   */
  vaultProviderBtcPubkey: string;

  /**
   * Vault keeper BTC public keys (x-only, 64-char hex).
   * Can be provided with or without "0x" prefix (will be stripped automatically).
   */
  vaultKeeperBtcPubkeys: readonly string[];

  /**
   * Universal challenger BTC public keys (x-only, 64-char hex).
   * Can be provided with or without "0x" prefix (will be stripped automatically).
   */
  universalChallengerBtcPubkeys: readonly string[];

  /**
   * CSV timelock in blocks for the PegIn vault output.
   */
  timelockPegin: number;

  /**
   * CSV timelock in blocks for the Pre-PegIn HTLC refund path.
   */
  timelockRefund: number;

  /**
   * SHA256 hash commitment(s) for the HTLC (64 hex chars = 32 bytes each).
   * Generated by the depositor as H = SHA256(secret).
   * For single deposits, pass a single-element array.
   */
  hashlocks: readonly string[];

  /**
   * Protocol fee rate in sat/vB from the contract offchain params.
   * Used by WASM for computing depositorClaimValue and min pegin fee.
   */
  protocolFeeRate: bigint;

  /**
   * Mempool fee rate in sat/vB for funding the Pre-PegIn transaction.
   * Used for UTXO selection and change calculation.
   */
  mempoolFeeRate: number;

  /**
   * M in M-of-N council multisig (from contract params).
   */
  councilQuorum: number;

  /**
   * N in M-of-N council multisig (from contract params).
   */
  councilSize: number;

  /**
   * Available UTXOs from the depositor's wallet for funding the Pre-PegIn transaction.
   */
  availableUTXOs: readonly UTXO[];

  /**
   * Bitcoin address for receiving change from the Pre-PegIn transaction.
   */
  changeAddress: string;
}

/**
 * Result of preparing a pegin.
 */
/** Per-vault PegIn data derived from a shared Pre-PegIn transaction */
export interface PerVaultPeginData {
  /** Index of the HTLC output in the Pre-PegIn transaction (0, 1, 2, ...) */
  htlcVout: number;
  /** HTLC output value in satoshis */
  htlcValue: bigint;
  /** Depositor-signed PegIn transaction hex (for contract registration) */
  peginTxHex: string;
  /** PegIn transaction ID */
  peginTxid: string;
  /** Depositor's Schnorr signature over PegIn input (HTLC leaf 0) */
  peginInputSignature: string;
  /** Vault output scriptPubKey hex */
  vaultScriptPubKey: string;
}

export interface PreparePeginResult {
  /** Funded but unsigned Pre-PegIn transaction hex */
  fundedPrePeginTxHex: string;
  /** Funded Pre-PegIn transaction ID */
  prePeginTxid: string;
  /** Unfunded Pre-PegIn transaction hex (for contract DA submission) */
  unsignedPrePeginTxHex: string;
  /** Per-vault PegIn data — one entry per hashlock/amount */
  perVault: PerVaultPeginData[];
  /** UTXOs selected to fund the Pre-PegIn transaction */
  selectedUTXOs: UTXO[];
  /** Transaction fee in satoshis */
  fee: bigint;
  /** Change amount in satoshis (if any) */
  changeAmount: bigint;
}


/**
 * Parameters for signing and broadcasting a transaction.
 */
export interface SignAndBroadcastParams {
  /**
   * Funded Pre-PegIn transaction hex from preparePegin().
   */
  fundedPrePeginTxHex: string;

  /**
   * Depositor's BTC public key (x-only, 64-char hex).
   * Can be provided with or without "0x" prefix.
   * Required for Taproot signing.
   */
  depositorBtcPubkey: string;

  /**
   * Optional pre-fetched prevout data for inputs not yet in the mempool.
   * Key format: "txid:vout" (e.g. "abc123...def:0").
   * When provided, matching inputs skip the mempool API fetch.
   * Useful for split transactions where outputs are unconfirmed.
   */
  localPrevouts?: Record<string, { scriptPubKey: string; value: number }>;
}

/**
 * Parameters for registering a peg-in on Ethereum.
 */
export interface RegisterPeginParams {
  /**
   * Depositor's BTC public key (x-only, 64-char hex).
   * Can be provided with or without "0x" prefix.
   */
  depositorBtcPubkey: string;

  /**
   * Unsigned Pre-PegIn transaction hex (submitted to contract for data availability).
   */
  unsignedPrePeginTx: string;

  /**
   * Depositor-signed PegIn transaction hex (submitted to contract; vault ID derived from this).
   */
  depositorSignedPeginTx: string;

  /**
   * Vault provider's Ethereum address.
   */
  vaultProvider: Address;

  /**
   * SHA256 hashlock for HTLC activation (bytes32 hex with 0x prefix).
   */
  hashlock: Hex;

  /**
   * Optional callback invoked after PoP signing completes but before ETH transaction.
   */
  onPopSigned?: () => void | Promise<void>;

  /**
   * Depositor's BTC payout address (e.g. bc1p..., bc1q...).
   * Converted to scriptPubKey internally via bitcoinjs-lib.
   *
   * If omitted, defaults to the connected BTC wallet's address
   * via `btcWallet.getAddress()`.
   */
  depositorPayoutBtcAddress?: string;

  /** Keccak256 hash of the depositor's WOTS public key (bytes32) */
  depositorWotsPkHash: Hex;

  /**
   * Pre-signed BTC PoP signature (hex with 0x prefix).
   * When provided, the BTC wallet signing step is skipped and this signature is used directly.
   * Useful for multi-vault deposits where PoP only needs to be signed once.
   */
  preSignedBtcPopSignature?: Hex;

  /**
   * Zero-based index of the HTLC output in the Pre-PegIn transaction that
   * this PegIn spends. In a batch Pre-PegIn with N HTLC outputs, each vault
   * registration references a different htlcVout (0..N-1).
   */
  htlcVout: number;
}

/**
 * Result of registering a peg-in on Ethereum.
 */
export interface RegisterPeginResult {
  /**
   * Ethereum transaction hash for the peg-in registration.
   */
  ethTxHash: Hash;

  /**
   * Derived vault ID: keccak256(abi.encode(peginTxHash, depositor)).
   * Used for contract reads/writes and indexer queries.
   */
  vaultId: Hex;

  /**
   * Raw Bitcoin pegin transaction hash (double-SHA256 of the signed pegin tx).
   * Used for VP RPC operations which key on the BTC transaction ID.
   */
  peginTxHash: Hex;

  /**
   * The BTC PoP signature used for this registration (hex with 0x prefix).
   * Returned so callers can reuse it for subsequent pegins without re-signing.
   */
  btcPopSignature: Hex;
}

/**
 * Single request in a batch pegin registration.
 * All requests in a batch share the same vault provider and depositor.
 */
export interface BatchPeginRequestItem {
  /** Depositor's BTC public key (x-only, 64-char hex or with 0x prefix) */
  depositorBtcPubkey: string;
  /** Unsigned Pre-PegIn tx hex (same for all vaults in batch) */
  unsignedPrePeginTx: string;
  /** Signed PegIn tx hex for this vault */
  depositorSignedPeginTx: string;
  /** SHA256 hashlock for HTLC activation (bytes32 hex) */
  hashlock: Hex;
  /** Zero-based HTLC output index in the Pre-PegIn tx */
  htlcVout: number;
  /** Depositor's BTC payout address (required — funds are sent here on payout) */
  depositorPayoutBtcAddress: string;
  /** Keccak256 hash of the depositor's WOTS public key (bytes32) */
  depositorWotsPkHash: Hex;
}

/**
 * Parameters for registerPeginBatchOnChain.
 */
export interface RegisterPeginBatchParams {
  /** Vault provider address (shared across all vaults in batch) */
  vaultProvider: Address;
  /** Individual pegin requests (one per vault) */
  requests: BatchPeginRequestItem[];
  /** Pre-signed BTC PoP signature (signed once, reused for all vaults) */
  preSignedBtcPopSignature?: Hex;
  /** Called after PoP is signed (before ETH tx) */
  onPopSigned?: () => void | Promise<void>;
}

/**
 * Per-vault result from a batch pegin registration.
 */
export interface BatchPeginResultItem {
  /** Derived vault ID: keccak256(abi.encode(peginTxHash, depositor)) */
  vaultId: Hex;
  /** Raw BTC pegin transaction hash */
  peginTxHash: Hex;
}

/**
 * Result of registering a batch of pegins on Ethereum in a single transaction.
 */
export interface RegisterPeginBatchResult {
  /** Ethereum transaction hash */
  ethTxHash: Hex;
  /** Per-vault results (same order as input requests) */
  vaults: BatchPeginResultItem[];
  /** The BTC PoP signature used (for reference) */
  btcPopSignature: Hex;
}

/**
 * Resolve prevout data for a transaction input.
 * Checks localPrevouts first; falls back to mempool API.
 */
function resolveUtxoInfo(
  txid: string,
  vout: number,
  localPrevouts: Record<string, { scriptPubKey: string; value: number }> | undefined,
  apiUrl: string,
): Promise<UtxoInfo> {
  const local = localPrevouts?.[`${txid}:${vout}`];
  if (local) {
    return Promise.resolve({
      txid,
      vout,
      value: local.value,
      scriptPubKey: local.scriptPubKey,
    });
  }
  return getUtxoInfo(txid, vout, apiUrl);
}

/**
 * Manager for orchestrating peg-in operations.
 *
 * This manager provides a high-level API for creating peg-in transactions
 * by coordinating between SDK primitives, utilities, and wallet interfaces.
 *
 * @remarks
 * The complete peg-in flow consists of 4 steps:
 *
 * | Step | Method | Description |
 * |------|--------|-------------|
 * | 1 | {@link preparePegin} | Build Pre-PegIn HTLC, fund it, sign PegIn input |
 * | 2 | {@link registerPeginOnChain} | Submit to Ethereum contract with PoP |
 * | 3 | {@link PayoutManager} | Sign BOTH payout authorizations |
 * | 4 | {@link signAndBroadcast} | Sign and broadcast Pre-PegIn tx to Bitcoin network |
 *
 * **Important:** Step 3 uses {@link PayoutManager}, not this class. After step 2,
 * the vault provider prepares 3 transactions per claimer:
 * - `claim_tx` - Claim transaction
 * - `assert_tx` - Assert transaction
 * - `payout_tx` - Payout transaction
 *
 * You must sign the Payout transaction for each claimer:
 * - {@link PayoutManager.signPayoutTransaction} - uses assert_tx as input reference
 *
 * Submit all signatures to the vault provider before proceeding to step 4.
 *
 * @see {@link PayoutManager} - Required for Step 3 (payout authorization)
 * @see {@link buildPrePeginPsbt} - Lower-level primitive for custom implementations
 * @see {@link https://github.com/babylonlabs-io/babylon-toolkit/blob/main/packages/babylon-ts-sdk/docs/quickstart/managers.md | Managers Quickstart}
 */
/**
 * Maximum time (ms) to wait for a transaction receipt before timing out.
 * Matches the prior vault-service polling timeout so users see a clear error
 * instead of an indefinite hang when a transaction is dropped from the mempool.
 */
const RECEIPT_TIMEOUT_MS = 120_000;

export class PeginManager {
  private readonly config: PeginManagerConfig;

  /**
   * Creates a new PeginManager instance.
   *
   * @param config - Manager configuration including wallets and contract addresses
   */
  constructor(config: PeginManagerConfig) {
    this.config = config;
  }

  /**
   * Prepares a peg-in by building the Pre-PegIn HTLC transaction,
   * funding it, constructing the PegIn transaction, and signing the PegIn input.
   *
   * This method orchestrates the following steps:
   * 1. Get depositor BTC public key from wallet
   * 2. Build unfunded Pre-PegIn transaction (HTLC output) using primitives
   * 3. Select UTXOs to cover the HTLC value
   * 4. Fund the Pre-PegIn transaction
   * 5. Derive the PegIn transaction from the funded Pre-PegIn tx
   * 6. Build PSBT for signing the PegIn input (HTLC leaf 0)
   * 7. Sign via BTC wallet and extract depositor signature
   *
   * The returned `fundedPrePeginTxHex` is funded but unsigned (inputs unsigned).
   * Use `signAndBroadcast()` AFTER registering on Ethereum to broadcast it.
   *
   * @param params - Pegin parameters including amount, HTLC params, UTXOs
   * @returns Pegin result with funded Pre-PegIn tx, signed PegIn input, and signatures
   * @throws Error if wallet operations fail or insufficient funds
   */
  async preparePegin(
    params: PreparePeginParams,
  ): Promise<PreparePeginResult> {
    // Step 1: Get depositor BTC public key from wallet
    const depositorBtcPubkeyRaw = await this.config.btcWallet.getPublicKeyHex();
    // Convert 33-byte compressed (66 chars) to 32-byte x-only (64 chars) if needed
    const depositorBtcPubkey =
      depositorBtcPubkeyRaw.length === 66
        ? depositorBtcPubkeyRaw.slice(2)
        : depositorBtcPubkeyRaw;

    const vaultProviderBtcPubkey = stripHexPrefix(params.vaultProviderBtcPubkey);
    const vaultKeeperBtcPubkeys = params.vaultKeeperBtcPubkeys.map(stripHexPrefix);
    const universalChallengerBtcPubkeys =
      params.universalChallengerBtcPubkeys.map(stripHexPrefix);

    if (params.hashlocks.length !== params.amounts.length) {
      throw new Error(
        `hashlocks.length (${params.hashlocks.length}) must equal amounts.length (${params.amounts.length})`,
      );
    }
    if (params.hashlocks.length === 0) {
      throw new Error("hashlocks must contain at least one entry");
    }

    const numLocalChallengers = vaultKeeperBtcPubkeys.length;

    const prePeginParams: PrePeginParams = {
      depositorPubkey: depositorBtcPubkey,
      vaultProviderPubkey: vaultProviderBtcPubkey,
      vaultKeeperPubkeys: vaultKeeperBtcPubkeys,
      universalChallengerPubkeys: universalChallengerBtcPubkeys,
      hashlocks: params.hashlocks,
      timelockRefund: params.timelockRefund,
      pegInAmounts: params.amounts,
      feeRate: params.protocolFeeRate,
      numLocalChallengers,
      councilQuorum: params.councilQuorum,
      councilSize: params.councilSize,
      network: this.config.btcNetwork,
    };

    // Step 2: Build unfunded Pre-PegIn transaction (N HTLC outputs, no inputs)
    const prePeginResult = await buildPrePeginPsbt(prePeginParams);

    // Step 3: Select UTXOs to cover ALL unfunded tx outputs (HTLCs + CPFP anchor)
    const utxoSelection = selectUtxosForPegin(
      [...params.availableUTXOs],
      prePeginResult.totalOutputValue,
      params.mempoolFeeRate,
      peginOutputCount(prePeginResult.htlcValues.length),
    );

    // Step 4: Fund the Pre-PegIn transaction with selected UTXOs
    const network = getNetwork(this.config.btcNetwork);
    const fundedPrePeginTxHex = fundPeginTransaction({
      unfundedTxHex: prePeginResult.psbtHex,
      selectedUTXOs: utxoSelection.selectedUTXOs,
      changeAddress: params.changeAddress,
      changeAmount: utxoSelection.changeAmount,
      network,
    });

    const prePeginTxid = stripHexPrefix(calculateBtcTxHash(fundedPrePeginTxHex));

    // Step 5: For each HTLC output, derive PegIn tx and build PSBT (no signing yet)
    const peginTxResults: Array<{
      txHex: string;
      txid: string;
      vaultScriptPubKey: string;
    }> = [];
    const psbtsToSign: string[] = [];
    const signOptions: SignPsbtOptions[] = [];

    for (let i = 0; i < params.hashlocks.length; i++) {
      const peginTxResult = await buildPeginTxFromFundedPrePegin({
        prePeginParams,
        timelockPegin: params.timelockPegin,
        fundedPrePeginTxHex,
        htlcVout: i,
      });

      const peginInputPsbtResult = await buildPeginInputPsbt({
        peginTxHex: peginTxResult.txHex,
        fundedPrePeginTxHex,
        depositorPubkey: depositorBtcPubkey,
        vaultProviderPubkey: vaultProviderBtcPubkey,
        vaultKeeperPubkeys: vaultKeeperBtcPubkeys,
        universalChallengerPubkeys: universalChallengerBtcPubkeys,
        hashlock: params.hashlocks[i],
        timelockRefund: params.timelockRefund,
        network: this.config.btcNetwork,
      });

      peginTxResults.push(peginTxResult);
      psbtsToSign.push(peginInputPsbtResult.psbtHex);
      signOptions.push(
        createTaprootScriptPathSignOptions(depositorBtcPubkeyRaw, 1),
      );
    }

    // Step 6: Batch sign all PegIn input PSBTs (single signPsbts call where supported)
    const signedPsbts = await this.signPsbtsWithFallback(
      psbtsToSign,
      signOptions,
    );

    // Step 7: Extract signatures and finalize
    const perVault: PerVaultPeginData[] = [];
    for (let i = 0; i < signedPsbts.length; i++) {
      const peginInputSignature = extractPeginInputSignature(
        signedPsbts[i],
        depositorBtcPubkey,
      );

      const depositorSignedPeginTxHex = finalizePeginInputPsbt(signedPsbts[i]);

      perVault.push({
        htlcVout: i,
        htlcValue: prePeginResult.htlcValues[i],
        peginTxHex: depositorSignedPeginTxHex,
        peginTxid: peginTxResults[i].txid,
        peginInputSignature,
        vaultScriptPubKey: peginTxResults[i].vaultScriptPubKey,
      });
    }

    return {
      fundedPrePeginTxHex,
      prePeginTxid,
      unsignedPrePeginTxHex: prePeginResult.psbtHex,
      perVault,
      selectedUTXOs: utxoSelection.selectedUTXOs,
      fee: utxoSelection.fee,
      changeAmount: utxoSelection.changeAmount,
    };
  }

  /**
   * Signs multiple PSBTs using batch signing if available, falling back to sequential signing.
   *
   * Wallets that support native batch signing (e.g. UniSat) will sign all PSBTs
   * in a single interaction. Others (e.g. Ledger, AppKit) implement signPsbts
   * by looping signPsbt internally, so the UX depends on the wallet adapter.
   */
  private async signPsbtsWithFallback(
    psbtsHexes: string[],
    options: SignPsbtOptions[],
  ): Promise<string[]> {
    if (typeof this.config.btcWallet.signPsbts === "function") {
      const signedPsbts = await this.config.btcWallet.signPsbts(
        psbtsHexes,
        options,
      );
      if (signedPsbts.length !== psbtsHexes.length) {
        throw new Error(
          `Expected ${psbtsHexes.length} signed PSBTs but received ${signedPsbts.length}`,
        );
      }
      return signedPsbts;
    }

    // Fallback: sign sequentially
    const signedPsbts: string[] = [];
    for (let i = 0; i < psbtsHexes.length; i++) {
      const signed = await this.config.btcWallet.signPsbt(
        psbtsHexes[i],
        options[i],
      );
      signedPsbts.push(signed);
    }
    return signedPsbts;
  }

  /**
   * Signs and broadcasts a funded peg-in transaction to the Bitcoin network.
   *
   * This method:
   * 1. Parses the funded transaction hex
   * 2. Fetches UTXO data from mempool for each input
   * 3. Creates a PSBT with proper witnessUtxo/tapInternalKey
   * 4. Signs via btcWallet.signPsbt()
   * 5. Finalizes and extracts the transaction
   * 6. Broadcasts via mempool API
   *
   * @param params - Transaction hex and depositor public key
   * @returns The broadcasted Bitcoin transaction ID
   * @throws Error if signing or broadcasting fails
   */
  async signAndBroadcast(params: SignAndBroadcastParams): Promise<string> {
    const { fundedPrePeginTxHex, depositorBtcPubkey } = params;

    // Step 1: Parse the funded transaction
    const cleanHex = fundedPrePeginTxHex.startsWith("0x")
      ? fundedPrePeginTxHex.slice(2)
      : fundedPrePeginTxHex;
    const tx = Transaction.fromHex(cleanHex);

    if (tx.ins.length === 0) {
      throw new Error("Transaction has no inputs");
    }

    // Step 2: Create PSBT and add inputs with UTXO data from mempool
    const psbt = new Psbt();
    psbt.setVersion(tx.version);
    psbt.setLocktime(tx.locktime);

    // Strip 0x prefix if present before converting to Buffer
    const cleanPubkey = depositorBtcPubkey.startsWith("0x")
      ? depositorBtcPubkey.slice(2)
      : depositorBtcPubkey;
    // Validate x-only pubkey length and format (32 bytes = 64 hex chars)
    if (cleanPubkey.length !== 64 || !/^[0-9a-fA-F]+$/.test(cleanPubkey)) {
      throw new Error(
        "Invalid depositorBtcPubkey: expected 64 hex characters (x-only pubkey)",
      );
    }
    const publicKeyNoCoord = Buffer.from(cleanPubkey, "hex");
    if (publicKeyNoCoord.length !== 32) {
      throw new Error(
        `Invalid depositorBtcPubkey length: expected 32 bytes, got ${publicKeyNoCoord.length}`,
      );
    }
    const apiUrl = this.config.mempoolApiUrl;

    // Resolve prevout data for each input (local cache or mempool API)
    const utxoDataPromises = tx.ins.map((input) => {
      const txid = Buffer.from(input.hash).reverse().toString("hex");
      const vout = input.index;
      return resolveUtxoInfo(txid, vout, params.localPrevouts, apiUrl).then(
        (utxoData) => ({ input, utxoData, txid, vout }),
      );
    });

    const inputsWithUtxoData = await Promise.all(utxoDataPromises);

    // Cross-validate: total input value must cover total output value.
    // A mismatch indicates the mempool API returned manipulated UTXO data,
    // which could lead to fee-siphoning or invalid signatures.
    const totalInputValue = inputsWithUtxoData.reduce(
      (sum, i) => sum + BigInt(i.utxoData.value),
      0n,
    );
    const totalOutputValue = tx.outs.reduce(
      (sum, out) => sum + BigInt(out.value),
      0n,
    );
    if (totalInputValue < totalOutputValue) {
      throw new Error(
        `UTXO value mismatch: total input value (${totalInputValue} sat) is less than ` +
          `total output value (${totalOutputValue} sat). ` +
          `This may indicate the mempool API returned manipulated UTXO data.`,
      );
    }

    // Add inputs with proper PSBT fields based on script type
    for (const { input, utxoData, txid, vout } of inputsWithUtxoData) {
      const psbtInputFields = getPsbtInputFields(
        {
          txid,
          vout,
          value: utxoData.value,
          scriptPubKey: utxoData.scriptPubKey,
        },
        publicKeyNoCoord,
      );

      psbt.addInput({
        hash: input.hash,
        index: input.index,
        sequence: input.sequence,
        ...psbtInputFields,
      });
    }

    // Step 3: Add outputs
    for (const output of tx.outs) {
      psbt.addOutput({
        script: output.script,
        value: output.value,
      });
    }

    // Step 4: Sign PSBT via wallet
    const signedPsbtHex = await this.config.btcWallet.signPsbt(psbt.toHex());
    const signedPsbt = Psbt.fromHex(signedPsbtHex);

    // Step 5: Finalize and extract transaction
    try {
      signedPsbt.finalizeAllInputs();
    } catch (e) {
      // Some wallets (e.g. UniSat, OKX) auto-finalize PSBTs before returning them.
      // Attempting to finalize again throws, which is expected and safe to skip —
      // but verify the wallet actually finalized all inputs.
      const allFinalized = signedPsbt.data.inputs.every(
        (inp) => inp.finalScriptWitness || inp.finalScriptSig,
      );
      if (!allFinalized) {
        throw new Error(
          `PSBT finalization failed and wallet did not auto-finalize: ${e}`,
        );
      }
    }

    const signedTxHex = signedPsbt.extractTransaction().toHex();

    // Step 6: Broadcast to Bitcoin network
    const btcTxid = await pushTx(signedTxHex, apiUrl);

    return btcTxid;
  }

  /**
   * Registers a peg-in on Ethereum by calling the BTCVaultRegistry contract.
   *
   * This method:
   * 1. Gets depositor ETH address from wallet
   * 2. Creates proof of possession (BTC signature of ETH address)
   * 3. Checks if vault already exists (pre-flight check)
   * 4. Encodes the contract call using viem
   * 5. Estimates gas (catches contract errors early with proper revert reasons)
   * 6. Sends transaction with pre-estimated gas via ethWallet.sendTransaction()
   *
   * @param params - Registration parameters including BTC pubkey and unsigned tx
   * @returns Result containing Ethereum transaction hash and vault ID
   * @throws Error if signing or transaction fails
   * @throws Error if vault already exists
   * @throws Error if contract simulation fails (e.g., invalid signature, unauthorized)
   */
  async registerPeginOnChain(
    params: RegisterPeginParams,
  ): Promise<RegisterPeginResult> {
    const {
      depositorBtcPubkey,
      unsignedPrePeginTx,
      depositorSignedPeginTx,
      vaultProvider,
      hashlock,
      htlcVout,
      onPopSigned,
      depositorPayoutBtcAddress,
      depositorWotsPkHash,
      preSignedBtcPopSignature,
    } = params;

    // Step 1: Get depositor ETH address (from wallet account)
    if (!this.config.ethWallet.account) {
      throw new Error("Ethereum wallet account not found");
    }
    const depositorEthAddress = this.config.ethWallet.account.address;

    // Step 2: Create proof of possession (or reuse pre-signed one)
    const btcPopSignature = await this.resolvePopSignature(
      depositorEthAddress,
      preSignedBtcPopSignature,
    );

    if (onPopSigned) {
      await onPopSigned();
    }

    // Step 3: Format parameters for contract call
    const depositorBtcPubkeyHex = ensureHexPrefix(depositorBtcPubkey);
    const unsignedPrePeginTxHex = ensureHexPrefix(unsignedPrePeginTx);
    const depositorSignedPeginTxHex = ensureHexPrefix(depositorSignedPeginTx);

    const payoutScriptPubKey = await this.resolvePayoutScriptPubKey(
      depositorPayoutBtcAddress,
    );

    // Step 4: Calculate pegin tx hash and derive vault ID, then check if it already exists
    const peginTxHash = calculateBtcTxHash(depositorSignedPeginTxHex);
    const derivedVaultIdHex = await deriveVaultId(
      stripHexPrefix(peginTxHash),
      stripHexPrefix(depositorEthAddress),
    );
    const vaultId = ensureHexPrefix(derivedVaultIdHex) as Hex;
    const exists = await this.checkVaultExists(vaultId);

    if (exists) {
      throw new Error(
        `Vault already exists (ID: ${vaultId}, peginTxHash: ${peginTxHash}). ` +
          `Vault IDs are derived from the pegin transaction hash and depositor address. ` +
          `To create a new vault, use different UTXOs or a different amount to generate a unique transaction.`,
      );
    }

    // Step 5: Query required pegin fee from the contract
    const publicClient = createPublicClient({
      chain: this.config.ethChain,
      transport: http(),
    });

    let peginFee: bigint;
    try {
      peginFee = (await publicClient.readContract({
        address: this.config.vaultContracts.btcVaultRegistry,
        abi: BTCVaultRegistryABI,
        functionName: "getPegInFee",
        args: [vaultProvider],
      })) as bigint;
    } catch {
      throw new Error(
        "Failed to query pegin fee from the contract. " +
          "Please check your network connection and that the contract address is correct.",
      );
    }

    // Step 6: Encode the contract call data
    const callData = encodeFunctionData({
      abi: BTCVaultRegistryABI,
      functionName: "submitPeginRequest",
      args: [
        depositorEthAddress,
        depositorBtcPubkeyHex,
        btcPopSignature,
        unsignedPrePeginTxHex,
        depositorSignedPeginTxHex,
        vaultProvider,
        hashlock,
        htlcVout,
        payoutScriptPubKey,
        depositorWotsPkHash,
      ],
    });

    // Step 7: Estimate gas first to catch contract errors before showing wallet popup
    // This ensures users see actual contract revert reasons instead of gas errors
    // The gas estimate is then passed to sendTransaction to avoid double estimation
    let gasEstimate: bigint;
    try {
      gasEstimate = await publicClient.estimateGas({
        to: this.config.vaultContracts.btcVaultRegistry,
        data: callData,
        value: peginFee,
        account: this.config.ethWallet.account.address,
      });
    } catch (error) {
      // Estimation failed - handle contract error with actual revert reason
      handleContractError(error); // always throws (return type: never)
    }

    // Step 8: Submit peg-in request to contract (estimation passed)
    let ethTxHash: Hex;
    try {
      // Send transaction with pre-estimated gas to skip internal estimation
      // Note: viem's sendTransaction uses `gas`, not `gasLimit`
      ethTxHash = await this.config.ethWallet.sendTransaction({
        to: this.config.vaultContracts.btcVaultRegistry,
        data: callData,
        value: peginFee,
        account: this.config.ethWallet.account,
        chain: this.config.ethChain,
        gas: gasEstimate,
      });
    } catch (error) {
      // Use proper error handler for better error messages
      handleContractError(error); // always throws (return type: never)
    }

    // Step 9: Wait for transaction receipt and verify it was not reverted
    const receipt = await publicClient.waitForTransactionReceipt({
      hash: ethTxHash,
      timeout: RECEIPT_TIMEOUT_MS,
    });
    if (receipt.status === "reverted") {
      handleContractError(
        new Error(
          `Transaction reverted. Hash: ${ethTxHash}. ` +
            `Check the transaction on block explorer for details.`,
        ),
      );
    }

    return {
      ethTxHash: receipt.transactionHash,
      vaultId,
      peginTxHash,
      btcPopSignature,
    };
  }

  /**
   * Register multiple pegins on Ethereum in a single transaction.
   *
   * Uses the contract's submitPeginRequestBatch() to submit all vault
   * registrations atomically. All vaults must share the same vault provider.
   * The PoP signature is signed once and included in each request.
   *
   * @param params - Batch registration parameters
   * @returns Batch result with per-vault IDs and single ETH tx hash
   */
  async registerPeginBatchOnChain(
    params: RegisterPeginBatchParams,
  ): Promise<RegisterPeginBatchResult> {
    const { vaultProvider, requests, preSignedBtcPopSignature, onPopSigned } =
      params;

    if (requests.length === 0) {
      throw new Error("Batch pegin requires at least one request");
    }

    // Step 1: Get depositor ETH address
    if (!this.config.ethWallet.account) {
      throw new Error("Ethereum wallet account not found");
    }
    const depositorEthAddress = this.config.ethWallet.account.address;

    // Step 2: Create proof of possession (or reuse pre-signed one)
    const btcPopSignature = await this.resolvePopSignature(
      depositorEthAddress,
      preSignedBtcPopSignature,
    );

    if (onPopSigned) {
      await onPopSigned();
    }

    // Step 3: Resolve per-request payout scriptPubKey.
    const resolvedPayoutScripts: Hex[] = [];
    for (const req of requests) {
      resolvedPayoutScripts.push(
        await this.resolvePayoutScriptPubKey(req.depositorPayoutBtcAddress),
      );
    }

    // Step 4: Pre-compute vault IDs and check for duplicates
    const vaultResults: BatchPeginResultItem[] = [];
    for (const req of requests) {
      const depositorSignedPeginTxHex = ensureHexPrefix(
        req.depositorSignedPeginTx,
      );
      const peginTxHash = calculateBtcTxHash(depositorSignedPeginTxHex);
      const derivedVaultIdHex = await deriveVaultId(
        stripHexPrefix(peginTxHash),
        stripHexPrefix(depositorEthAddress),
      );
      const vaultId = ensureHexPrefix(derivedVaultIdHex) as Hex;
      const exists = await this.checkVaultExists(vaultId);
      if (exists) {
        throw new Error(
          `Vault already exists (ID: ${vaultId}, peginTxHash: ${peginTxHash}). ` +
            `To create a new vault, use different UTXOs or a different amount.`,
        );
      }
      vaultResults.push({ vaultId, peginTxHash });
    }

    // Step 5: Query pegin fee and compute total
    const publicClient = createPublicClient({
      chain: this.config.ethChain,
      transport: http(),
    });

    let peginFee: bigint;
    try {
      peginFee = (await publicClient.readContract({
        address: this.config.vaultContracts.btcVaultRegistry,
        abi: BTCVaultRegistryABI,
        functionName: "getPegInFee",
        args: [vaultProvider],
      })) as bigint;
    } catch {
      throw new Error(
        "Failed to query pegin fee from the contract. " +
          "Please check your network connection and that the contract address is correct.",
      );
    }
    const totalFee = peginFee * BigInt(requests.length);

    // Step 6: Build BatchPeginRequest[] tuple array
    const batchRequests = requests.map((req, i) => ({
      depositorBtcPubKey: ensureHexPrefix(req.depositorBtcPubkey) as Hex,
      btcPopSignature: btcPopSignature as Hex,
      unsignedPrePeginTx: ensureHexPrefix(req.unsignedPrePeginTx) as Hex,
      depositorSignedPeginTx: ensureHexPrefix(
        req.depositorSignedPeginTx,
      ) as Hex,
      hashlock: req.hashlock,
      htlcVout: req.htlcVout,
      referralCode: NO_REFERRAL_CODE,
      depositorPayoutBtcAddress: resolvedPayoutScripts[i],
      depositorWotsPkHash: req.depositorWotsPkHash,
    }));

    // Step 7: Encode batch call data
    const callData = encodeFunctionData({
      abi: BTCVaultRegistryABI,
      functionName: "submitPeginRequestBatch",
      args: [depositorEthAddress, vaultProvider, batchRequests],
    });

    // Step 8: Estimate gas
    let gasEstimate: bigint;
    try {
      gasEstimate = await publicClient.estimateGas({
        to: this.config.vaultContracts.btcVaultRegistry,
        data: callData,
        value: totalFee,
        account: this.config.ethWallet.account.address,
      });
    } catch (error) {
      handleContractError(error); // always throws (return type: never)
    }

    // Step 9: Submit batch transaction
    let ethTxHash: Hex;
    try {
      ethTxHash = await this.config.ethWallet.sendTransaction({
        to: this.config.vaultContracts.btcVaultRegistry,
        data: callData,
        value: totalFee,
        account: this.config.ethWallet.account,
        chain: this.config.ethChain,
        gas: gasEstimate,
      });
    } catch (error) {
      handleContractError(error); // always throws (return type: never)
    }

    // Step 10: Wait for receipt
    const receipt = await publicClient.waitForTransactionReceipt({
      hash: ethTxHash,
      timeout: RECEIPT_TIMEOUT_MS,
    });
    if (receipt.status === "reverted") {
      handleContractError(
        new Error(
          `Batch transaction reverted. Hash: ${ethTxHash}. ` +
            `Check the transaction on block explorer for details.`,
        ),
      );
    }

    return {
      ethTxHash: receipt.transactionHash,
      vaults: vaultResults,
      btcPopSignature,
    };
  }

  /**
   * Check if a vault already exists for a given vault ID.
   *
   * @param vaultId - The Bitcoin transaction hash (vault ID)
   * @returns True if vault exists, false otherwise
   */
  private async checkVaultExists(vaultId: Hex): Promise<boolean> {
    try {
      // Create a public client to read from the contract
      const publicClient = createPublicClient({
        chain: this.config.ethChain,
        transport: http(),
      });

      const result = (await publicClient.readContract({
        address: this.config.vaultContracts.btcVaultRegistry,
        abi: BTCVaultRegistryABI,
        functionName: "getBtcVaultBasicInfo",
        args: [vaultId],
      })) as readonly [Address, ...unknown[]];

      // First element is depositor; if not zero address, vault exists
      return result[0] !== zeroAddress;
    } catch {
      // If reading fails, assume vault doesn't exist and let contract handle it
      return false;
    }
  }

  /**
   * Resolve the BTC payout address to a scriptPubKey hex for the contract.
   *
   * If a payout address is provided, converts it directly.
   * If omitted, uses the wallet's address and validates it against the
   * wallet's public key to guard against a compromised wallet provider.
   */
  private async resolvePayoutScriptPubKey(
    depositorPayoutBtcAddress?: string,
  ): Promise<Hex> {
    let address: string;

    if (depositorPayoutBtcAddress) {
      address = depositorPayoutBtcAddress;
    } else {
      address = await this.config.btcWallet.getAddress();
      const walletPubkey = await this.config.btcWallet.getPublicKeyHex();
      if (
        !isAddressFromPublicKey(
          address,
          walletPubkey,
          this.config.btcNetwork,
        )
      ) {
        throw new Error(
          "The BTC address from your wallet does not match the wallet's public key. " +
            "Please ensure your wallet is using a supported address type (Taproot or Native SegWit).",
        );
      }
    }

    const network = getNetwork(this.config.btcNetwork);
    try {
      return `0x${bitcoin.address.toOutputScript(address, network).toString("hex")}` as Hex;
    } catch {
      throw new Error(
        `Invalid BTC payout address: "${address}". ` +
          `Please provide a valid Bitcoin address for the ${this.config.btcNetwork} network.`,
      );
    }
  }

  /**
   * Resolve or create a BTC Proof-of-Possession signature.
   *
   * Reuses a pre-signed signature when provided (e.g. multi-vault deposits),
   * otherwise signs a BIP-322 message with the BTC wallet.
   */
  private async resolvePopSignature(
    depositorEthAddress: Address,
    preSignedBtcPopSignature?: Hex,
  ): Promise<Hex> {
    if (preSignedBtcPopSignature) {
      return preSignedBtcPopSignature;
    }

    // Message format matches BTCProofOfPossession.sol buildMessage()
    const verifyingContract = this.config.vaultContracts.btcVaultRegistry;
    const popMessage = `${depositorEthAddress.toLowerCase()}:${this.config.ethChain.id}:pegin:${verifyingContract.toLowerCase()}`;
    const btcPopSignatureRaw = await this.config.btcWallet.signMessage(
      popMessage,
      "bip322-simple",
    );

    // BTC wallets return base64, Ethereum contracts expect hex
    if (btcPopSignatureRaw.startsWith("0x")) {
      return btcPopSignatureRaw as Hex;
    }
    const signatureBytes = Buffer.from(btcPopSignatureRaw, "base64");
    return `0x${signatureBytes.toString("hex")}` as Hex;
  }

  /**
   * Gets the configured Bitcoin network.
   *
   * @returns The Bitcoin network (mainnet, testnet, signet, regtest)
   */
  getNetwork(): Network {
    return this.config.btcNetwork;
  }

  /**
   * Gets the configured BTCVaultRegistry contract address.
   *
   * @returns The Ethereum address of the BTCVaultRegistry contract
   */
  getVaultContractAddress(): Address {
    return this.config.vaultContracts.btcVaultRegistry;
  }
}
