/**
 * Shared golden-vector fixtures for server-identity tests.
 *
 * Generated by running the btc-vault Rust reference
 * (`crates/btc-auth/src/server_identity.rs::build_server_identity_payload`
 * + BIP-322 sign with `BtcSignerLocal::dummy_signer_seeded(7)`).
 *
 * Reproduce: add a temporary `#[test]` to that module that prints the
 * four hex strings (ephemeral_pubkey_compressed, signing_key_xonly,
 * payload_hex, signature_hex), run
 * `cargo test --manifest-path /path/to/btc-vault/Cargo.toml -p btc-auth
 * --lib <test> -- --nocapture --exact`, then revert.
 *
 * IMPORTANT: each constant below is a single-line string literal.
 * Do NOT split these strings across lines with `+` concatenation —
 * a previous bug introduced when this file was line-wrapped silently
 * dropped/duplicated hex characters at line boundaries.
 */

/** Ephemeral pubkey (compressed SEC1, 33B) from `dummy_signer_seeded(42)`. */
export const GOLDEN_EPHEMERAL_PUBKEY_COMPRESSED =
  "02f0a1c73ec9606112027b881656190772b770f5b81bbf86840dbb88779de3158f";

/** Persistent signing key x-only (32B) from `dummy_signer_seeded(7)`. */
export const GOLDEN_SIGNING_KEY_XONLY =
  "49164a02ac81b42cc4dcde7a8311becf56886850f063a86c66afef5c8ae0778c";

/** The u64 signed over. */
export const GOLDEN_EXPIRES_AT = 1_700_000_000;

/**
 * The CBOR-encoded server-identity payload (signed over).
 *
 * Layout (123 bytes / 246 hex chars):
 *   83                 — array(3) outer
 *   98 1b              — array(27) for the domain string "btc-auth.server-identity.v1"
 *   <27 CBOR uints>    — each ASCII byte encoded as a CBOR small/u8 uint
 *   98 21              — array(33) for the compressed ephemeral pubkey
 *   <33 CBOR uints>    — each pubkey byte encoded as a CBOR small/u8 uint
 *   1a 65 53 f1 00     — u32 expires_at = 1_700_000_000 (0x6553f100)
 *
 * NOTE: ciborium serializes `&[u8]` and `Vec<u8>` here as CBOR arrays of
 * u8 (not byte strings) because the payload tuple types are
 * `(&[u8], Vec<u8>, u64)` — the slice/vec elements are emitted as
 * individual CBOR uints. Don't switch the encoder to byte-string output.
 */
export const GOLDEN_PAYLOAD_HEX =
  "83981b186218741863182d1861187518741868182e187318651872187618651872182d186918641865186e1874186918741879182e1876183198210218f018a118c7183e18c9186018611202187b1888161856181907187218b7187018f518b8181b18bf188618840d18bb18881877189d18e315188f1a6553f100";

/** 64-byte BIP-322 Schnorr signature for the above payload + signing key. */
export const GOLDEN_SIGNATURE_HEX =
  "89c7473a2b4128f7c015272d535c535d7508b8ca9d9a06e4863d7da4cea8feb99fc20f9cbbb49f67594a81fdd31406f9654e4964b9176e8d47259a0fbc322fdf";

/*
 * --- CWT bearer-token golden vectors ---
 *
 * Real ES256K COSE Sign1 CWT tokens produced by the btc-vault Rust
 * reference (`crates/btc-auth/src/token_signer.rs::build_cose_sign1_token`
 * + `coset::cwt::ClaimsSetBuilder`). They are signed by the **same**
 * ephemeral key as {@link GOLDEN_EPHEMERAL_PUBKEY_COMPRESSED} (seed 42)
 * and carry {@link GOLDEN_SIGNING_KEY_XONLY} (seed 7) as their `iss`, so
 * a token verifies against the server-identity golden above as one
 * consistent issuance.
 *
 * Reproduce: add a temporary `#[test]` to that module that builds a
 * COSE Sign1 over a `ClaimsSetBuilder` payload with the seed-42 signing
 * key, iss = seed-7 x-only, aud = seed-99 x-only, and prints the
 * base64url token. Run with
 * `cargo test -p btc-auth --lib --features test-utils <test> -- --nocapture`,
 * then revert.
 *
 * Claims (all three tokens): iss = GOLDEN_SIGNING_KEY_XONLY,
 * aud = GOLDEN_CWT_AUDIENCE_XONLY, iat = nbf = GOLDEN_CWT_NBF.
 */

/** Depositor x-only pubkey carried in the `aud` claim (seed 99). */
export const GOLDEN_CWT_AUDIENCE_XONLY =
  "4f401063cc0f559467937a3fad43929058922478886f70505e7d29569af2ab5e";

/** `iat`/`nbf` of every CWT golden token. */
export const GOLDEN_CWT_NBF = 1_699_996_000;
/** `exp` of the normal-lifetime tokens. ≤ GOLDEN_EXPIRES_AT (server-identity expiry). */
export const GOLDEN_CWT_EXP = 1_699_999_000;
/** `exp` of the short-lifetime token used to exercise refresh-on-skew. */
export const GOLDEN_CWT_SHORT_EXP = 1_699_996_440;

/** JSON-RPC-subject token (`sub` = "vaultd-jsonrpc"), exp = GOLDEN_CWT_EXP. */
export const GOLDEN_CWT_TOKEN_JSONRPC =
  "0oREoQE4LqBYu6cBeEA0OTE2NGEwMmFjODFiNDJjYzRkY2RlN2E4MzExYmVjZjU2ODg2ODUwZjA2M2E4NmM2NmFmZWY1YzhhZTA3NzhjAm52YXVsdGQtanNvbnJwYwN4QDRmNDAxMDYzY2MwZjU1OTQ2NzkzN2EzZmFkNDM5MjkwNTg5MjI0Nzg4ODZmNzA1MDVlN2QyOTU2OWFmMmFiNWUEGmVT7RgFGmVT4WAGGmVT4WAHUKurq6urq6urq6urq6urq6tYQFYf_JPwc-IvtuwABdhlKk78PWG0KS2u30pRQ2U1CE4GHGrfmcLIrhZsoDifabPwgtcMLTuDEUHLGJM5dOC_Bi8";

/** Same issuance shape but short-lived (exp = GOLDEN_CWT_SHORT_EXP). */
export const GOLDEN_CWT_TOKEN_JSONRPC_SHORT =
  "0oREoQE4LqBYu6cBeEA0OTE2NGEwMmFjODFiNDJjYzRkY2RlN2E4MzExYmVjZjU2ODg2ODUwZjA2M2E4NmM2NmFmZWY1YzhhZTA3NzhjAm52YXVsdGQtanNvbnJwYwN4QDRmNDAxMDYzY2MwZjU1OTQ2NzkzN2EzZmFkNDM5MjkwNTg5MjI0Nzg4ODZmNzA1MDVlN2QyOTU2OWFmMmFiNWUEGmVT4xgFGmVT4WAGGmVT4WAHUM3Nzc3Nzc3Nzc3Nzc3Nzc1YQDayqqB4bTlHAaFOwyNcAMIEpiBW5GrgnkarO0yJ7bnkHjsmHlFcA9XDFupahH9wIQMGN8R6FVDax52MdYdg3Wc"; // ggignore: deterministic golden-vector test token, not a live credential

/** gRPC-subject token (`sub` = "vaultd-grpc"), exp = GOLDEN_CWT_EXP. */
export const GOLDEN_CWT_TOKEN_GRPC =
  "0oREoQE4LqBYuKcBeEA0OTE2NGEwMmFjODFiNDJjYzRkY2RlN2E4MzExYmVjZjU2ODg2ODUwZjA2M2E4NmM2NmFmZWY1YzhhZTA3NzhjAmt2YXVsdGQtZ3JwYwN4QDRmNDAxMDYzY2MwZjU1OTQ2NzkzN2EzZmFkNDM5MjkwNTg5MjI0Nzg4ODZmNzA1MDVlN2QyOTU2OWFmMmFiNWUEGmVT7RgFGmVT4WAGGmVT4WAHUO_v7-_v7-_v7-_v7-_v7-9YQJhF3CJH5sFKdi7jwGeqVxErk95edujMvMVF6JiU-Io6cbBBbcJtHWZPF_Cc3_SIlAO6s6Oi9N6u0XUOPQf5ZW8"; // ggignore: deterministic golden-vector test token, not a live credential
